# download at https://api.cirrus-ci.com/v1/artifact/github/electronstudio/jaylib/main/binary.zip


task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  env:
    RAYLIB_PLATFORM: macosx-arm64
    RAYLIB_VERSION: 5.0.0-0
  setup_script:
    - brew update
    - brew install java11
    - sudo ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
    - export CPPFLAGS="-I/opt/homebrew/opt/openjdk@11/include"
  build_raylib_script:
    - git submodule update --init --recursive
    - cd raylib
    - mkdir build
    - cd build
    - cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
    - make -j8
    - sudo make install
  build_script:
    - ./build-java.sh
    - ./build-native.sh
  artifacts:
    path: "./*macos*.jar"