# download at https://api.cirrus-ci.com/v1/artifact/github/electronstudio/jaylib/main/binary.zip


task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
  env:
    RAYLIB_PLATFORM: macosx-arm64
  setup_script:
    - brew update
    - brew install java11
    - sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
  build_raylib_script:
    - git submodule update --init --recursive
    - cd raylib
    - mkdir build
    - cd build
    - cmake -DBUILD_EXAMPLES=off -DINCLUDE_EVERYTHING=on -DSUPPORT_FILEFORMAT_JPG=on -DWITH_PIC=on -DCMAKE_BUILD_TYPE=Release ..
    - make -j8
    - sudo make install
  build_script:
    - ./build-java.sh
    - ./build-native.sh
  artifacts:
    path: "./*macos*.jar"